num_to_category = Dict([

2 =>   Ammo,
3 =>   Arrows,
4 =>   Bolts,
5 =>   Construction materials,
6 =>   Construction products,
7 =>   Cooking ingredients,
8 =>   Costumes,
9 =>   Crafting materials,
10 =>  Familiars,
11 =>  Farming produce,
12 =>  Fletching materials,
13 =>  Food and Drink,
14 =>  Herblore materials,
15 =>  Hunting equipment,
16 =>  Hunting Produce,
17 =>  Jewellery,
18 =>  Mage armour,
19 =>  Mage weapons,
20 =>  Melee armour - low level,
21 =>  Melee armour - mid level,
22 =>  Melee armour - high level,
23 =>  Melee weapons - low level,
24 =>  Melee weapons - mid level,
25 =>  Melee weapons - high level,
26 =>  Mining and Smithing,
27 =>  Potions,
28 =>  Prayer armour,
29 =>  Prayer materials,
30 =>  Range armour,
31 =>  Range weapons,
32 =>  Runecrafting,
33 =>  Runes, Spells and Teleports,
34 =>  Seeds,
35 =>  Summoning scrolls,
36 =>  Tools and containers,
37 =>  Woodcutting product,
38 =>  Pocket items,
39 =>  Stone spirits,
40 =>  Salvage,
41 =>  Firemaking products,
])

category_to_num = Dict(value => key for (key, value) in num_to_category)
